openapi: 3.0.0
info:
  title: Instructor Course Management APIs
  description: 'APIs designed to manage courses content including videos, quizzes, and PPTs for instructors.'
  version: 1.0.0
servers:
  - url: /v1/instructor/course
    description: Production server
paths:
  /videos:
    get:
      summary: Retrieve a list of videos.
      description: This endpoint retrieves a list of videos with their names and thumbnail URLs.
      tags:
        - Videos
      operationId: getVideos
      responses:
        '200':
          description: A list of videos
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VideosResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Create a new video.
      description: This endpoint allows for the addition of a new video with a name and thumbnail URL.
      tags:
        - Videos
      operationId: createVideo
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewVideoRequest'
      responses:
        '201':
          description: Video created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Video'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /quizzes:
    get:
      summary: Retrieve a list of quizzes.
      description: This endpoint retrieves a list of quiz names available to the instructor.
      tags:
        - Quizzes
      operationId: getQuizzes
      responses:
        '200':
          description: A list of quizzes
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QuizzesResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Create a new quiz.
      description: This endpoint allows for the creation of a new quiz with a specific name.
      tags:
        - Quizzes
      operationId: createQuiz
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewQuizRequest'
      responses:
        '201':
          description: Quiz created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Quiz'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /ppts:
    get:
      summary: Retrieve a list of PPTs.
      description: This endpoint retrieves a list of PPTs with their names.
      tags:
        - PPTs
      operationId: getPPTs
      responses:
        '200':
          description: A list of PPTs
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PPTsResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Create a new PPT.
      description: This endpoint allows for the addition of a new PPT with a specific name.
      tags:
        - PPTs
      operationId: createPPT
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewPPTRequest'
      responses:
        '201':
          description: PPT created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PPT'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    VideosResponse:
      type: object
      properties:
        videos:
          type: array
          items:
            $ref: '#/components/schemas/Video'
    QuizzesResponse:
      type: object
      properties:
        quizzes:
          type: array
          items:
            type: string
    PPTsResponse:
      type: object
      properties:
        ppts:
          type: array
          items:
            type: string
    NewVideoRequest:
      type: object
      properties:
        name:
          type: string
          description: The name of the video.
    NewQuizRequest:
      type: object
      properties:
        name:
          type: string
          description: The name of the quiz.
        video_ids:
          type: array
          items:
            type: string
          description: A list of video IDs associated with this quiz.
    NewPPTRequest:
      type: object
      properties:
        name:
          type: string
          description: The name of the PPT.
        video_ids:
          type: array
          items:
            type: string
          description: A list of video IDs associated with this PPT.
    Video:
      type: object
      properties:
        name:
          type: string
          description: The name of the video.
        thumbnail_url:
          type: string
          description: URL to the thumbnail image for the video.
        id:
          type: string
          description: Video ID
        video_url:
          type: string
          description: URL of the video
    Quiz:
      type: object
      properties:
        name:
          type: string
          description: The name of the quiz.
        id:
          type: string
          description: Quiz ID
    PPT:
      type: object
      properties:
        name:
          type: string
          description: The name of the PPT.
        thumbnail_url:
          type: string
          description: URL to the thumbnail image for the ppt.
        id:
          type: string
          description: PPT ID
    Error:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string