info:
  description: APIs designed to manage enrolled and recommended courses.
  title: Course Management APIs
  version: 1.0.0
openapi: 3.0.0
servers:
  - url: /v1/courses
    description: Base path for course-level operations
paths:
  /:
    get:
      summary: Endpoint to retrieve courses filtered by course id(optional).
      description: 'This endpoint retrieves a list of courses that the user has access to. It includes a thumbnail image, summary, rating for each course, the course name, and the course ID.'
      operationId: getCourses
      parameters:
        - in: query
          name: id
          schema:
            type: string
          description: Course id
      responses:
        '200':
          description: A list of courses (can be filtered by id)
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Course'
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Unauthorized
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Unexpected error
      tags:
      - Courses
    post:
      description: 'This endpoint allows for the creation of a new course with specific attributes like course name and course tags.'
      operationId: createCourse
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewCourseRequest'
        description: The course data to create
        required: true
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Course'
          description: Course created
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Bad request
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Unauthorized
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Unexpected error
      summary: Endpoint to create a new course.
      tags:
      - Courses
  /recommended:
    get:
      summary: Endpoint to retrieve recommended courses for the student.
      description: 'This endpoint retrieves a list of recommended courses for a student. It includes a summary, rating, thumbnail image for each course, the course name, and the course ID.'
      tags:
        - Recommended Courses
      responses:
        '200':
          description: A list of recommended courses
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Course'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Course:
      type: object
      properties:
        id:
          description: The unique identifier for the course.
          type: string
        name:
          description: The name of the course.
          type: string
        thumbnail_url:
          description: URL to the thumbnail image for the course.
          type: string
        summary:
          description: Summary for the course.
          type: string
        rating:
          description: Rating for the course.
          type: integer
    NewCourseRequest:
      type: object
      properties:
        name:
          description: The name of the course.
          type: string
        summary:
          description: A summary for the new course.
          type: string
        tags:
          description: A list of tags associated with the course.
          items:
            type: string
          type: array
    Error:
      properties:
        code:
          format: int32
          type: integer
        message:
          type: string
      type: object
