openapi: 3.0.0
info:
  version: "1.0.0"
  title: course-info
  description: The API for getting course info for the student
servers:
  - url: /v1/student
paths:
  /courseinfo:
    get:
      summary: Get course information by ID
      description: >
        This API takes in a course ID as a query parameter and returns
        information about the course.
      operationId: getCourseInfo
      parameters:
        - in: query
          name: id
          required: true
          schema:
            type: string
          description: The ID of the course to retrieve information for.
      responses:
        '200':
          description: Course information retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Course'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Course not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Course:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        summary:
          type: string
        thumbnail_url:
          type: string
        rating:
          type: integer
        
    Error:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string