components:
  schemas:
    Course:
      properties:
        id:
          description: The unique identifier for the course.
          type: string
        name:
          description: The name of the course.
          type: string
        thumbnail_url:
          description: URL to the thumbnail image for the course.
          type: string
      type: object
    CoursesResponse:
      properties:
        courses:
          items:
            $ref: '#/components/schemas/Course'
          type: array
      type: object
    Error:
      properties:
        code:
          format: int32
          type: integer
        message:
          type: string
      type: object
    NewCourseRequest:
      properties:
        name:
          description: The name of the course.
          type: string
        summary:
          description: A summary for the new course.
          type: string
        tags:
          description: A list of tags associated with the course.
          items:
            type: string
          type: array
      type: object
    NewPPTRequest:
      properties:
        name:
          description: The name of the PPT.
          type: string
        video_ids:
          description: A list of video IDs associated with this PPT.
          items:
            type: string
          type: array
      type: object
    NewQuizRequest:
      properties:
        name:
          description: The name of the quiz.
          type: string
        video_ids:
          description: A list of video IDs associated with this quiz.
          items:
            type: string
          type: array
      type: object
    NewVideoRequest:
      properties:
        name:
          description: The name of the video.
          type: string
        video_file:
          type: string
          format: binary
          description: The actual video file.
      type: object
    PPT:
      properties:
        id:
          description: PPT ID
          type: string
        name:
          description: The name of the PPT.
          type: string
        thumbnail_url:
          description: URL to the thumbnail image for the ppt.
          type: string
      type: object
    PPTsResponse:
      properties:
        ppts:
          items:
            type: string
          type: array
      type: object
    Quiz:
      properties:
        id:
          description: Quiz ID
          type: string
        name:
          description: The name of the quiz.
          type: string
      type: object
    QuizzesResponse:
      properties:
        quizzes:
          items:
            type: string
          type: array
      type: object
    Video:
      properties:
        id:
          description: Video ID
          type: string
        name:
          description: The name of the video.
          type: string
        thumbnail_url:
          description: URL to the thumbnail image for the video.
          type: string
        video_url:
          description: URL of the video
          type: string
      type: object
    VideosResponse:
      properties:
        videos:
          items:
            $ref: '#/components/schemas/Video'
          type: array
      type: object
info:
  description: APIs designed to manage courses content including videos, quizzes,
    and PPTs for instructors.
  title: Instructor Course Management APIs
  version: 1.0.0
openapi: 3.0.0
paths:
  /courses:
    get:
      description: 'This endpoint retrieves a list of courses that an instructor has
        access to. It includes a thumbnail image for each course, the course name,
        and the course ID.

        '
      operationId: getCourses
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CoursesResponse'
          description: A list of courses
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Unauthorized
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Unexpected error
      summary: Endpoint to retrieve courses for the instructor.
      tags:
      - Courses
    post:
      description: 'This endpoint allows for the creation of a new course with specific
        attributes like course name and course tags.

        '
      operationId: createCourse
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewCourseRequest'
        description: The course data to create
        required: true
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Course'
          description: Course created
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Bad request
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Unauthorized
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Unexpected error
      summary: Endpoint to create a new course.
      tags:
      - Courses
  /courses/ppts:
    get:
      description: This endpoint retrieves a list of PPTs with their names.
      operationId: getPPTs
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PPTsResponse'
          description: A list of PPTs
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Bad Request
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Unauthorized
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Forbidden
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Not Found
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Internal Server Error
      summary: Retrieve a list of PPTs.
      tags:
      - PPTs
    post:
      description: This endpoint allows for the addition of a new PPT with a specific
        name.
      operationId: createPPT
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewPPTRequest'
        required: true
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PPT'
          description: PPT created
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Bad Request
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Unauthorized
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Forbidden
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Internal Server Error
      summary: Create a new PPT.
      tags:
      - PPTs
  /courses/quizzes:
    get:
      description: This endpoint retrieves a list of quiz names available to the instructor.
      operationId: getQuizzes
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QuizzesResponse'
          description: A list of quizzes
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Bad Request
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Unauthorized
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Forbidden
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Not Found
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Internal Server Error
      summary: Retrieve a list of quizzes.
      tags:
      - Quizzes
    post:
      description: This endpoint allows for the creation of a new quiz with a specific
        name.
      operationId: createQuiz
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewQuizRequest'
        required: true
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Quiz'
          description: Quiz created
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Bad Request
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Unauthorized
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Forbidden
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Internal Server Error
      summary: Create a new quiz.
      tags:
      - Quizzes
  /courses/videos:
    get:
      description: This endpoint retrieves a list of videos with their names and thumbnail
        URLs.
      operationId: getVideos
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VideosResponse'
          description: A list of videos
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Bad Request
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Unauthorized
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Forbidden
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Not Found
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Internal Server Error
      summary: Retrieve a list of videos.
      tags:
      - Videos
    post:
      description: This endpoint allows for the addition of a new video with a name
        and thumbnail URL.
      operationId: createVideo
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewVideoRequest'
        required: true
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Video'
          description: Video created
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Bad Request
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Unauthorized
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Forbidden
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Internal Server Error
      summary: Create a new video.
      tags:
      - Videos
servers:
- description: Production server
  url: /v1/instructor